"""
services/blockchain_service.py
Web3.py integration layer for the EnvironmentalCredit ERC-721 contract.

Responsibilities:
  - Connect to Ethereum node (Sepolia or any EVM-compatible RPC).
  - Sign and broadcast transactions using the configured admin wallet.
  - Expose clean Python methods that routes/credit_service can call.
"""
import json
import os
from pathlib import Path
from typing import Optional

from web3 import Web3
from web3.middleware import ExtraDataToPOAMiddleware

from config import Config


# ---------------------------------------------------------------------------
# ABI loading
# ---------------------------------------------------------------------------

_ABI_PATH = Path(__file__).parent.parent / "contracts" / "EnvironmentalCredit_abi.json"


def _load_abi() -> list:
    """Load the contract ABI from the JSON file generated by Hardhat/Remix."""
    if not _ABI_PATH.exists():
        raise FileNotFoundError(
            f"Contract ABI not found at {_ABI_PATH}. "
            "Run `npx hardhat compile` and copy the ABI to "
            "backend/contracts/EnvironmentalCredit_abi.json"
        )
    with open(_ABI_PATH, "r", encoding="utf-8") as fh:
        return json.load(fh)


# ---------------------------------------------------------------------------
# BlockchainService
# ---------------------------------------------------------------------------

class BlockchainService:
    """Thin wrapper around Web3.py for the EnvironmentalCredit contract."""

    def __init__(self) -> None:
        self.w3 = Web3(Web3.HTTPProvider(Config.ETH_RPC_URL))

        # Sepolia / POA chains need this middleware
        self.w3.middleware_onion.inject(ExtraDataToPOAMiddleware, layer=0)

        if not self.w3.is_connected():
            raise ConnectionError(
                f"Cannot connect to Ethereum node at {Config.ETH_RPC_URL!r}"
            )

        self.account = self.w3.eth.account.from_key(Config.WALLET_PRIVATE_KEY)
        self.contract = self.w3.eth.contract(
            address=Web3.to_checksum_address(Config.CONTRACT_ADDRESS),
            abi=_load_abi(),
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _build_and_send(self, fn) -> str:
        """
        Build a transaction from a contract function call, sign it with the
        admin wallet, broadcast it, and return the transaction hash hex string.
        """
        nonce = self.w3.eth.get_transaction_count(self.account.address)
        tx = fn.build_transaction(
            {
                "from": self.account.address,
                "nonce": nonce,
                "gas": 300_000,
                "gasPrice": self.w3.eth.gas_price,
            }
        )
        signed = self.w3.eth.account.sign_transaction(tx, self.account.key)
        tx_hash = self.w3.eth.send_raw_transaction(signed.raw_transaction)
        return tx_hash.hex()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def mint_credit(self, to_address: str, project_id: int) -> dict:
        """
        Mint a new environmental credit NFT.

        Args:
            to_address: Recipient Ethereum wallet address.
            project_id: Integer project identifier (matches off-chain DB).

        Returns:
            {"token_id": int, "tx_hash": str}
        """
        to_checksum = Web3.to_checksum_address(to_address)
        fn = self.contract.functions.mintCredit(to_checksum, project_id)
        tx_hash = self._build_and_send(fn)

        # Fetch the receipt to extract the token ID from the CreditMinted event
        receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash, timeout=120)
        logs = self.contract.events.CreditMinted().process_receipt(receipt)
        token_id = logs[0]["args"]["tokenId"] if logs else None

        return {"token_id": token_id, "tx_hash": tx_hash}

    def retire_credit(self, token_id: int) -> str:
        """
        Retire a credit permanently (must be called by the token owner).
        The admin wallet is assumed to own the credit at retirement time.

        Returns:
            tx_hash (str)
        """
        fn = self.contract.functions.retireCredit(token_id)
        return self._build_and_send(fn)

    def transfer_credit(self, token_id: int, to_address: str) -> str:
        """
        Transfer a credit using the standard ERC-721 safeTransferFrom.

        Returns:
            tx_hash (str)
        """
        from_address = self.account.address
        to_checksum = Web3.to_checksum_address(to_address)
        fn = self.contract.functions.safeTransferFrom(from_address, to_checksum, token_id)
        return self._build_and_send(fn)

    def get_token_owner(self, token_id: int) -> str:
        """Return the current owner address of a token."""
        return self.contract.functions.ownerOf(token_id).call()

    def is_retired(self, token_id: int) -> bool:
        """Return True if the token has been retired."""
        return self.contract.functions.isRetired(token_id).call()

    def get_token_project(self, token_id: int) -> int:
        """Return the projectId stored on-chain for the given token."""
        return self.contract.functions.tokenProject(token_id).call()


# ---------------------------------------------------------------------------
# Module-level singleton (lazy)
# ---------------------------------------------------------------------------

_instance: Optional[BlockchainService] = None


def get_blockchain_service() -> BlockchainService:
    """Return a lazily-initialised singleton BlockchainService."""
    global _instance
    if _instance is None:
        _instance = BlockchainService()
    return _instance
